name: Auto package for SCF
on:
  workflow_dispatch:
  push:
    branches:
      - main 
  create:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Check Out
      uses: actions/checkout@main  

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.1

    - name: Setup Node modules
      run: |
        npm install

    - name: Upload Package File
      uses: actions/upload-artifact@v2
      if: startsWith(github.ref, 'refs/heads/')
      with:
        name: genshin-dailynote-helper-serverless
        path: |
          ./lib/
          ./node_modules/
          ./app.js
          ./config.json.example
          ./LICENSE
          ./package.json
          ./README.md
          ./bootstrap
          ./scf_bootstrap

    - name: Pack Serverless for release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        zip -vr genshin-dailynote-helper-serverless.zip ./lib/ ./node_modules/ ./app.js ./config.json.example ./LICENSE ./package.json ./README.md ./bootstrap ./scf_bootstrap

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: genshin-dailynote-helper-serverless.zip