name: Auto package for SCF
on:
  workflow_dispatch:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Check Out
      uses: actions/checkout@main  

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.1

    - name: Setup Node modules
      run: |
        npm install

    - name: Upload Package File
      uses: actions/upload-artifact@v2
      with:
        name: SCF-Package
        path: |
          ./lib/
          ./node_modules/
          ./app.js
          ./config.json.example
          ./LICENSE
          ./package.json
          ./README.md
          ./tencent_scf_bootstrap